# Generated by Django 3.2.13 on 2023-09-19 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('company_code', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=255)),
                ('company_industry_code', models.IntegerField()),
                ('company_stock_code', models.CharField(max_length=10)),
            ],
        ),
    ]
