# Generated by Django 3.2.13 on 2023-09-20 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIndustry',
            fields=[
                ('company_industry_code', models.IntegerField(primary_key=True, serialize=False)),
                ('industry_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('company_code', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=255)),
                ('company_stock_code', models.CharField(max_length=10)),
                ('company_real_industry_code', models.CharField(max_length=10, null=True)),
                ('company_industry_code', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company', to='financialData.companyindustry')),
            ],
        ),
    ]
