# Generated by Django 3.2.13 on 2023-09-21 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financialData', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FinancialStatement',
        ),
    ]
