# Generated by Django 3.2.13 on 2023-09-20 06:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financialData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('current_assets', models.BigIntegerField()),
                ('non_current_assets', models.BigIntegerField()),
                ('total_assets_first', models.BigIntegerField()),
                ('total_assets_second', models.BigIntegerField()),
                ('total_assets_third', models.BigIntegerField()),
                ('current_liabilities', models.BigIntegerField()),
                ('non_current_liabilities', models.BigIntegerField()),
                ('total_liabilities_first', models.BigIntegerField()),
                ('total_liabilities_second', models.BigIntegerField()),
                ('total_liabilities_third', models.BigIntegerField()),
                ('capital', models.BigIntegerField()),
                ('total_equity', models.BigIntegerField()),
                ('revenue_first', models.BigIntegerField()),
                ('revenue_second', models.BigIntegerField()),
                ('revenue_third', models.BigIntegerField()),
                ('gross_profit', models.BigIntegerField()),
                ('operating_profit_first', models.BigIntegerField()),
                ('operating_profit_second', models.BigIntegerField()),
                ('operating_profit_third', models.BigIntegerField()),
                ('non_operating_income', models.BigIntegerField()),
                ('non_operating_expenses', models.BigIntegerField()),
                ('income_before_tax', models.BigIntegerField()),
                ('income_tax_expense', models.BigIntegerField()),
                ('net_income', models.BigIntegerField()),
                ('total_asset_growth_rate', models.FloatField()),
                ('revenue_asset_growth_rate', models.FloatField()),
                ('net_income_growth_rate', models.FloatField()),
                ('operating_profit_margin', models.FloatField()),
                ('roe', models.FloatField()),
                ('roic', models.FloatField()),
                ('debt_to_equity_ratio', models.FloatField()),
                ('interest_coverage_ratio', models.FloatField()),
                ('debt_dependency', models.FloatField()),
                ('accounts_receivable_turnover', models.FloatField()),
                ('inventory_turnover', models.FloatField()),
                ('total_asset_turnover', models.FloatField()),
                ('company_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to='financialData.company')),
            ],
        ),
    ]
