# Generated by Django 3.2.13 on 2023-09-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialData', '0003_alter_company_company_real_industry_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIndustry',
            fields=[
                ('company_industry_code', models.IntegerField(primary_key=True, serialize=False)),
                ('industry_name', models.CharField(max_length=255)),
            ],
        ),
    ]
