# Generated by Django 3.2.13 on 2023-09-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialData', '0003_financialstatement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_industry_code',
        ),
        migrations.AddField(
            model_name='company',
            name='company_industry_code',
            field=models.ManyToManyField(null=True, related_name='company', to='financialData.CompanyIndustry'),
        ),
    ]
