# Generated by Django 3.2.13 on 2023-09-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialData', '0004_auto_20230922_0251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_industry_code',
        ),
        migrations.AddField(
            model_name='company',
            name='company_industry',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CompanyIndustry',
        ),
    ]
