# Generated by Django 3.2.13 on 2023-09-24 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financialData', '0006_auto_20230924_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatement_2022',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('total_assets', models.BigIntegerField(default=0)),
                ('total_liabilities', models.BigIntegerField(default=0)),
                ('revenue', models.BigIntegerField(default=0)),
                ('operating_profit', models.BigIntegerField(default=0)),
                ('net_income', models.BigIntegerField(default=0)),
                ('company_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements_2022', to='financialData.company')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStatement_2021',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('revenue', models.BigIntegerField(default=0)),
                ('net_income', models.BigIntegerField(default=0)),
                ('company_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements_2021', to='financialData.company')),
            ],
        ),
    ]
