# Generated by Django 3.2.13 on 2023-09-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialData', '0007_financialstatement_2021_financialstatement_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialstatement',
            name='accounts_receivable_turnover',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='capital',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='current_assets',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='current_liabilities',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='debt_dependency',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='debt_to_equity_ratio',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='gross_profit',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='income_before_tax',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='income_tax_expense',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='interest_coverage_ratio',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='inventory_turnover',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='net_income',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='net_income_growth_rate',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='non_current_assets',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='non_current_liabilities',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='non_operating_expenses',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='non_operating_income',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='operating_profit',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='operating_profit_margin',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='revenue',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='revenue_asset_growth_rate',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='roe',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='roic',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='total_asset_growth_rate',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='total_asset_turnover',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='total_assets',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='total_equity',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement',
            name='total_liabilities',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement_2021',
            name='net_income',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement_2021',
            name='revenue',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement_2022',
            name='net_income',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement_2022',
            name='operating_profit',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement_2022',
            name='revenue',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement_2022',
            name='total_assets',
            field=models.BigIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='financialstatement_2022',
            name='total_liabilities',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
