# Generated by Django 3.2.13 on 2023-10-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialData', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProductRank10',
            fields=[
                ('seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('fin_prdt_nm', models.CharField(max_length=255, null=True)),
                ('kor_co_nm', models.CharField(max_length=255, null=True)),
                ('co_type_nm', models.CharField(max_length=255, null=True)),
                ('bank_type_nm', models.CharField(max_length=255, null=True)),
                ('intr_rate_type_nm', models.CharField(max_length=255, null=True)),
                ('save_trm', models.BigIntegerField(null=True)),
                ('intr_rate', models.FloatField(null=True)),
                ('intr_rate2', models.FloatField(null=True)),
                ('fin_prdt_cd', models.CharField(max_length=255, null=True)),
                ('spcl_cnd', models.CharField(max_length=255, null=True)),
                ('etc_note', models.CharField(max_length=255, null=True)),
                ('max_limit', models.BigIntegerField(null=True)),
                ('rsrv_type_nm', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
    ]
