# Generated by Django 3.2.13 on 2023-10-01 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('financialData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyindicators',
            name='company_seq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company_indicators', to='financialData.company'),
        ),
        migrations.AlterField(
            model_name='companyindicatorsscore',
            name='company_seq',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Company_indicators_score', to='financialData.company'),
        ),
    ]
