# Generated by Django 3.2.13 on 2023-10-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialData', '0002_financialproductrank10'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_image_url',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
