# Generated by Django 3.2.13 on 2023-09-24 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financialData', '0005_auto_20230922_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialstatement',
            old_name='net_income_2020',
            new_name='operating_profit',
        ),
        migrations.RenameField(
            model_name='financialstatement',
            old_name='net_income_2021',
            new_name='revenue',
        ),
        migrations.RenameField(
            model_name='financialstatement',
            old_name='operating_profit_first',
            new_name='total_assets',
        ),
        migrations.RenameField(
            model_name='financialstatement',
            old_name='operating_profit_second',
            new_name='total_liabilities',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='revenue_2020',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='revenue_2021',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='revenue_first',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='revenue_second',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='total_assets_first',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='total_assets_second',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='total_liabilities_first',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='total_liabilities_second',
        ),
    ]
