# Generated by Django 3.2.13 on 2023-09-26 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financialData', '0008_auto_20230924_2336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialstatement',
            name='company_seq',
        ),
        migrations.RemoveField(
            model_name='financialstatement_2021',
            name='company_seq',
        ),
        migrations.RemoveField(
            model_name='financialstatement_2022',
            name='company_seq',
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='FinancialStatement',
        ),
        migrations.DeleteModel(
            name='FinancialStatement_2021',
        ),
        migrations.DeleteModel(
            name='FinancialStatement_2022',
        ),
    ]
