# Generated by Django 3.2.13 on 2023-09-26 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financialData', '0009_auto_20230926_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('company_code', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=255)),
                ('company_stock_code', models.CharField(max_length=10)),
                ('company_real_industry_code', models.CharField(max_length=10, null=True)),
                ('company_industry', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStatement_2022',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('total_assets', models.BigIntegerField(default=None, null=True)),
                ('total_liabilities', models.BigIntegerField(default=None, null=True)),
                ('revenue', models.BigIntegerField(default=None, null=True)),
                ('operating_profit', models.BigIntegerField(default=None, null=True)),
                ('net_income', models.BigIntegerField(default=None, null=True)),
                ('company_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements_2022', to='financialData.company')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStatement_2021',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('revenue', models.BigIntegerField(default=None, null=True)),
                ('net_income', models.BigIntegerField(default=None, null=True)),
                ('company_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements_2021', to='financialData.company')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('current_assets', models.BigIntegerField(default=None, null=True)),
                ('non_current_assets', models.BigIntegerField(default=None, null=True)),
                ('total_assets', models.BigIntegerField(default=None, null=True)),
                ('current_liabilities', models.BigIntegerField(default=None, null=True)),
                ('non_current_liabilities', models.BigIntegerField(default=None, null=True)),
                ('total_liabilities', models.BigIntegerField(default=None, null=True)),
                ('capital', models.BigIntegerField(default=None, null=True)),
                ('total_equity', models.BigIntegerField(default=None, null=True)),
                ('revenue', models.BigIntegerField(default=None, null=True)),
                ('gross_profit', models.BigIntegerField(default=None, null=True)),
                ('operating_profit', models.BigIntegerField(default=None, null=True)),
                ('non_operating_income', models.BigIntegerField(default=None, null=True)),
                ('non_operating_expenses', models.BigIntegerField(default=None, null=True)),
                ('income_before_tax', models.BigIntegerField(default=None, null=True)),
                ('income_tax_expense', models.BigIntegerField(default=None, null=True)),
                ('net_income', models.BigIntegerField(default=None, null=True)),
                ('total_asset_growth_rate', models.FloatField(default=None, null=True)),
                ('revenue_asset_growth_rate', models.FloatField(default=None, null=True)),
                ('net_income_growth_rate', models.FloatField(default=None, null=True)),
                ('operating_profit_margin', models.FloatField(default=None, null=True)),
                ('roe', models.FloatField(default=None, null=True)),
                ('roic', models.FloatField(default=None, null=True)),
                ('debt_to_equity_ratio', models.FloatField(default=None, null=True)),
                ('interest_coverage_ratio', models.FloatField(default=None, null=True)),
                ('debt_dependency', models.FloatField(default=None, null=True)),
                ('accounts_receivable_turnover', models.FloatField(default=None, null=True)),
                ('inventory_turnover', models.FloatField(default=None, null=True)),
                ('total_asset_turnover', models.FloatField(default=None, null=True)),
                ('company_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_statements', to='financialData.company')),
            ],
        ),
    ]
