# Generated by Django 3.2.13 on 2023-09-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialData', '0010_company_financialstatement_financialstatement_2021_financialstatement_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialProduct',
            fields=[
                ('seq', models.BigAutoField(primary_key=True, serialize=False)),
                ('fin_prdt_nm', models.CharField(max_length=255)),
                ('kor_co_nm', models.CharField(max_length=255)),
                ('co_type_nm', models.CharField(max_length=255)),
                ('bank_type_nm', models.CharField(max_length=255)),
                ('intr_rate_type_nm', models.CharField(max_length=255)),
                ('save_trm', models.BigIntegerField()),
                ('intr_rate', models.FloatField()),
                ('intr_rate2', models.FloatField()),
                ('fin_prdt_cd', models.BigIntegerField()),
                ('join_way', models.CharField(max_length=255)),
                ('mtrt_int', models.CharField(max_length=255)),
                ('spcl_cnd', models.CharField(max_length=255)),
                ('join_member', models.CharField(max_length=255)),
                ('etc_note', models.CharField(max_length=255)),
                ('max_limit', models.BigIntegerField()),
            ],
        ),
    ]
