# Generated by Django 3.2.13 on 2023-09-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialData', '0011_financialproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialproduct',
            name='bank_type_nm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='co_type_nm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='etc_note',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='fin_prdt_cd',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='fin_prdt_nm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='intr_rate',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='intr_rate2',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='intr_rate_type_nm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='join_member',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='join_way',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='kor_co_nm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='max_limit',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='mtrt_int',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='save_trm',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='financialproduct',
            name='spcl_cnd',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
