# Generated by Django 3.2.13 on 2023-09-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialData', '0012_auto_20230926_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialproduct',
            name='fin_prdt_cd',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
