# Generated by Django 3.2.13 on 2023-09-27 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financialData', '0015_company_stock_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='stock_type',
            new_name='company_stock_type',
        ),
    ]
