# Generated by Django 3.2.13 on 2023-09-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financialData', '0016_rename_stock_type_company_company_stock_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIndicators',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('company_code_seq', models.IntegerField()),
                ('stability', models.IntegerField()),
                ('size', models.IntegerField()),
                ('growth', models.IntegerField()),
                ('profitability', models.IntegerField()),
                ('revenue_growth', models.FloatField()),
                ('debt_growth', models.FloatField()),
                ('operating_profit_growth', models.FloatField()),
                ('asset_growth', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='accounts_receivable_turnover',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='debt_dependency',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='interest_coverage_ratio',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='inventory_turnover',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='total_asset_turnover',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
