# Generated by Django 3.2.13 on 2023-09-30 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financialData', '0017_auto_20231001_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialstatement',
            name='non_operating_expenses',
        ),
        migrations.RemoveField(
            model_name='financialstatement',
            name='non_operating_income',
        ),
    ]
