export const CHART_TUTORIAL = {
  RED_CANDLE: 0,
  RED_CANDLE_BODY: 1,
  RED_CANDLE_DOWN: 2,
  RED_CANDLE_UP: 3,
  BLUE_CANDLE: 4,
  BLUE_CANDLE_BODY: 5,
  BLUE_CANDLE_DOWN: 6,
  BLUE_CANDLE_UP: 7,
};
